version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pf_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: usuarios_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usuarios_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: pf_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: inventario_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot --silent"]
      interval: 10s
      timeout: 5s
      retries: 15

volumes:
  pg_data:
  mysql_data:
